### ISSUE TITLE
Games not showing because of sorting order

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#62]
For example, if you open "All Steam games" tab and type in "getting", you'll get only one result, because the default sorting order is "Metascore". There are two other games with "getting" in the name that will show if you sort by "Game name".

I think that (1) sorting order shouldn't filter out results, and (2) the default sorting order should be "Game name".

**Comment by MakoSipper** [comment]
Maaaaybe include some easy-to-see message, like `Hiding ### games because of the current sorting method` or something like that? It took me a while to figure out why I couldn't find the "Getting Over It" game.

**Comment by gsabater** [comment]
Hello @MakoSipper 

I think you know we have been working in a new browser layout.
It's been a while because it had complex technical implications, but in this new layout we have been thinking on this suggestion and we have come to this. Please, tell us what you think. I hope you find this as useful as we do.

![one](https://user-images.githubusercontent.com/4948172/51417351-e34f5580-1b7d-11e9-93b1-f0d60137ede9.PNG)
![two](https://user-images.githubusercontent.com/4948172/51417354-e5b1af80-1b7d-11e9-98dd-9e26287f96b1.PNG)


This will be in the beta view in a few days, and will become the default browser in a month or two.

**Comment by MakoSipper** [comment]
It looks great to me, really.

**Comment by gsabater** [comment]
Nice. 

We plan on adding a message for each filter in the browser, so this is going to take a while.
Once is live I count on you to test it and tell us if there is something wrong.

I will close the issue once this goes live.
Thanks

**Comment by MakoSipper** [comment]
Count on me!

**Comment by gsabater** [comment]
As this is now the default layout, we will close this issue.
Reopen again or create a new issue if you encounter any problems.
