### ISSUE TITLE
Interface issue when editing colletion

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#67]
It's easier shown than explained, but the delete button is overlapped with the game name.
![chrome_2018-10-28_22-13-42](https://user-images.githubusercontent.com/16372995/47624801-edbdfe00-dafe-11e8-96a3-3f84d11343aa.png)

**Comment by gsabater** [comment]
Hello @MakoSipper

Thanks for the heads up. This bug is something I have been delaying for some weeks because I think the whole "create a collection" user interface is weak and could be vastly improved.

For now I will fix the issue, but I want to change the layout. As always, designing the interface is where I struggle the most on this site.

Thanks

**Comment by gsabater** [comment]
We have solved the button placement, and we have changed the layout a little bit.

---

Fixed in November release.
Complete changelog in https://steam-backlog.com/changelog

**Comment by MakoSipper** [comment]
Someone's been working hard ;)
