### ISSUE TITLE
[BETA] Visibility options

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#74]
"Hide games already in backlog" and "Show hidden games" options are missing from beta, in case you haven't noticed, or at least I couldn't find it for the life of me.

**Comment by gsabater** [comment]
Hello @MakoSipper 

Our first change of february has been including the visibility options in the beta layout.
You can try it at https://steam-backlog.com/app/beta

As always, tell us if you find anything wrong or if you need any help.

---

Fixed in February2019 release.
Complete changelog at https://steam-backlog.com/changelog
