### ISSUE TITLE
uBlock Origin hides "Login with STEAM" button

### ISSUE THREAD

**Issue by vogler** [gsabater/Steam-Backlog#90]
As mentioned in https://github.com/JosefNemec/Playnite/issues/1109
With uBlock Origin 1.22.2
![image](https://user-images.githubusercontent.com/493741/65587484-350a7400-df86-11e9-833c-28f4684ec670.png)
I get
![image](https://user-images.githubusercontent.com/493741/65587177-b7466880-df85-11e9-8c90-d08373a3047e.png)
After disabling it for the site I get
![image](https://user-images.githubusercontent.com/493741/65587261-e0ff8f80-df85-11e9-9e65-9b63ad5aa65d.png)

**Comment by gsabater** [comment]
Hello @vogler 
First of all, sorry for the late answer.

I have tried to reproduce the issue without luck I also have ublock origin (v 1.22.4) and the button is there for for me with it enabled and disabled.

I will make a few changes to the homepage and that button will have completely different styles and classnames, so when the new homepage is live im going to ask you if you can see it or not. This will tell us if the problem is the text, the URL or the class names, because i dont have a clue.

Thanks a lot for your feedback

**Comment by gsabater** [comment]
Hello Again @vogler 

I have updated the homepage and replaced all the login buttons across the whole website for a more "classical" button (just bootstrap primary).

Please, let me know if you still can't see the button, because I seem to see it even in incognito (with a new session) and with ublock activated. I left you a link here: https://steam-backlog.com

![login with ublock](https://user-images.githubusercontent.com/4948172/65979181-24ba3380-e475-11e9-8402-02b419b74b36.PNG)

Thanks a lot for your time and feedback

**Comment by vogler** [comment]
Button is there now with uBlock active 👍

**Comment by gsabater** [comment]
Thanks a lot for your time and feedback.
As a note , i think that ublock removed the button because that button has the classname "btn-social" and I guess that the extension thougth that the button was some kind of third party intrusive widget.

If you have any other suggestions or find any other bugs, please, use this channel or you can also use the discord. Thanks again

---

Fixed ~ September 2019
Complete changelog at https://steam-backlog.com/changelog
